### ISSUE TITLE
Filename with spaces fail to convert

### ISSUE THREAD

**Issue by MacNB** [chris1111/ICNS-Builder#1]
when drag-n-drop a file with spaces (e.g. "Apple11 copy.png") onto ICNS-Builder, there's no output file.
A temp folder can be seen created and it disappears quickly but there's no ICNS file.

**Comment by chris1111** [comment]
You right a file which contains a name with a space does not work and on the other hand a name which does not have any spaces it works.

I will investigate and you will say

**Comment by chris1111** [comment]
Fix [Release V3](https://github.com/chris1111/ICNS-Builder/releases/tag/V3)
Thanks for the catch 👍
